version: "3.5"
services:
  vtest:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOMAIN=${DOMAIN}
      - LOCALIP=${LOCALIP}
      - PASSWORD=${PASSWORD}
    ports:
      - "127.0.0.1:10080:80"
      - "53:53/udp"
    restart: always
    volumes:
      - ./vtest.db:/app/vtest.db
